package EmployeeManagementSystem.Controller;

import EmployeeManagementSystem.View.*;
import EmployeeManagementSystemDB.EmpDB;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;

public class AdminDashController {
    private AdminDashView view;
    private String adminName;

    public AdminDashController(AdminDashView view, String adminName) {
        this.view = view;
        this.adminName = adminName;

        this.view.getLblAdminName().setText(adminName);


        loadManagerTable();

        // image uploading
        this.view.getLblProfilePic().addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                JFileChooser chooser = new JFileChooser();
                if (chooser.showOpenDialog(view.mainPanel) == JFileChooser.APPROVE_OPTION) {
                    try {
                        ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getAbsolutePath());
                        int d = 130;
                        BufferedImage mask = new BufferedImage(d, d, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2 = mask.createGraphics();
                        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                        g2.fill(new Ellipse2D.Double(0, 0, d, d));
                        g2.setComposite(AlphaComposite.SrcIn);
                        g2.drawImage(icon.getImage(), 0, 0, d, d, null);
                        g2.dispose();
                        view.getLblProfilePic().setIcon(new ImageIcon(mask));
                        view.getLblProfilePic().setText("");
                        view.getLblProfilePic().setBorder(null);
                    } catch (Exception ex) { ex.printStackTrace(); }
                }
            }
        });

        // add manager
        this.view.getBtnAddManager().addActionListener(e -> showAddManagerDialog());

        // delete manager
        this.view.getBtnDelete().addActionListener(e -> {
            String id = JOptionPane.showInputDialog(view.mainPanel, "Enter Manager ID to Delete:");
            if (id != null && !id.trim().isEmpty()) {
                int confirm = JOptionPane.showConfirmDialog(view.mainPanel, "Delete Manager ID " + id + "?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    executeDelete(id);
                }
            }
        });

        // 4. GENERATE AWT REPORT
        this.view.getBtnReport().addActionListener(e -> generateAWTReport());

        // 5. LOGOUT
        this.view.getBtnLogout().addActionListener(e -> {
            if (JOptionPane.showConfirmDialog(view.mainPanel, "Log out from Admin Dashboard?", "Logout", JOptionPane.YES_NO_OPTION) == 0) {
                LoginView lv = new LoginView();
                new LoginController(lv);
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(view.mainPanel);
                frame.setContentPane(lv.mainPanel);
                frame.revalidate();
                frame.repaint();
            }
        });
    }

    private void generateAWTReport() {
        JDialog reportDialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(view.mainPanel), "Enterprise Summary Report", true);
        reportDialog.setSize(600, 750); // Increased height to fit departments

        JPanel reportPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // --- Drawing Header ---
                g2.setFont(new Font("Serif", Font.BOLD, 26));
                g2.drawString("STAFFSYNC ENTERPRISE REPORT", 70, 60);

                g2.setFont(new Font("SansSerif", Font.PLAIN, 12));
                g2.drawString("Generated by: " + adminName + " | Date: " + new java.util.Date(), 50, 90);
                g2.drawLine(50, 100, 530, 100);

                try (Connection conn = EmpDB.getConnection(); Statement st = conn.createStatement()) {
                    // 1. STRATEGIC SUMMARY
                    ResultSet rs1 = st.executeQuery("SELECT COUNT(*) FROM Employee");
                    rs1.next(); int totalCount = rs1.getInt(1);

                    ResultSet rs2 = st.executeQuery("SELECT SUM(Amount) FROM Payroll p JOIN Employee e ON p.P_Id = e.P_Id");
                    rs2.next(); double totalPayroll = rs2.getDouble(1);

                    g2.setFont(new Font("SansSerif", Font.BOLD, 16));
                    g2.drawString("STRATEGIC SUMMARY", 50, 140);
                    g2.setFont(new Font("SansSerif", Font.PLAIN, 14));
                    g2.drawString("- Total Registered Workforce: " + totalCount, 60, 170);
                    g2.drawString("- Total Monthly Salary Expense: Rs. " + String.format("%,.2f", totalPayroll), 60, 195);

                    // --- 2. DEPARTMENT HEADCOUNT (FIXED) ---
                    g2.setFont(new Font("SansSerif", Font.BOLD, 16));
                    g2.drawString("DEPARTMENT HEADCOUNT", 50, 250);

                    g2.setFont(new Font("Monospaced", Font.BOLD, 13));
                    g2.drawString(String.format("%-25s %-10s", "Department Name", "Staff Count"), 60, 280);
                    g2.drawLine(60, 285, 500, 285);

                    // This query fetches the departments and the count of employees in each
                    String deptSql = "SELECT d.Dep_Name, COUNT(e.Emp_ID) FROM Department d " +
                            "LEFT JOIN Employee e ON d.Dep_ID = e.Dep_ID GROUP BY d.Dep_Name";

                    ResultSet rs3 = st.executeQuery(deptSql);
                    int y = 310;
                    g2.setFont(new Font("Monospaced", Font.PLAIN, 12));

                    while (rs3.next()) {
                        String deptName = rs3.getString(1);
                        int count = rs3.getInt(2);
                        g2.drawString(String.format("%-25s %-10d", deptName, count), 60, y);
                        y += 25; // Spacing between rows
                    }

                    // --- Footer ---
                    g2.drawLine(50, y + 20, 530, y + 20);
                    g2.setFont(new Font("Serif", Font.ITALIC, 11));
                    g2.drawString("End of Official Document - NIBM Coursework 2026", 160, y + 50);

                } catch (Exception ex) {
                    g2.setColor(Color.RED);
                    g2.drawString("Database Error: " + ex.getMessage(), 60, 300);
                    ex.printStackTrace();
                }
            }
        };

        reportPanel.setBackground(Color.WHITE);
        reportDialog.add(reportPanel);
        reportDialog.setLocationRelativeTo(view.mainPanel);
        reportDialog.setVisible(true);
    }

    private void showAddManagerDialog() {
        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(view.mainPanel), "Add New Manager", true);
        dialog.setSize(350, 450);
        dialog.setLayout(new GridLayout(6, 1, 10, 10));
        ((JPanel)dialog.getContentPane()).setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JTextField txtId = new JTextField();
        JTextField txtName = new JTextField();
        JTextField txtEmail = new JTextField();
        JPasswordField txtPass = new JPasswordField();
        JButton btnSave = new JButton("Save Manager");

        dialog.add(new JLabel("Manager ID:")); dialog.add(txtId);
        dialog.add(new JLabel("Full Name:")); dialog.add(txtName);
        dialog.add(new JLabel("Email:")); dialog.add(txtEmail);
        dialog.add(new JLabel("Password:")); dialog.add(txtPass);
        dialog.add(new JLabel("")); dialog.add(btnSave);

        btnSave.addActionListener(ev -> {
            String id = txtId.getText().trim();
            String name = txtName.getText().trim();
            String email = txtEmail.getText().trim();
            String pass = new String(txtPass.getPassword()).trim();

            if(id.isEmpty() || name.isEmpty() || email.isEmpty() || pass.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "All fields are required!");
                return;
            }

            String sql = "INSERT INTO Employee (Emp_ID, Emp_Name, Emp_Email, Password, Role, Dep_ID, P_Id) VALUES (?, ?, ?, ?, 'Manager', 2, 1)";
            try (Connection conn = EmpDB.getConnection(); PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1, id);
                pst.setString(2, name);
                pst.setString(3, email);
                pst.setString(4, pass);

                if (pst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(dialog, "Manager Added Successfully!");
                    loadManagerTable();
                    dialog.dispose();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(dialog, "Database Error: " + ex.getMessage());
            }
        });

        dialog.setLocationRelativeTo(view.mainPanel);
        dialog.setVisible(true);
    }

    private void loadManagerTable() {
        DefaultTableModel model = view.getTableModel();
        if (model == null) return;
        model.setRowCount(0);

        String sql = "SELECT Emp_ID, Emp_Name, Emp_Email FROM Employee WHERE Role = 'Manager'";
        try (Connection conn = EmpDB.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getString("Emp_ID"),
                        rs.getString("Emp_Name"),
                        rs.getString("Emp_Email")
                });
            }
        } catch (SQLException ex) {
            System.err.println("Table Load Error: " + ex.getMessage());
        }
    }

    private void executeDelete(String id) {
        try (Connection conn = EmpDB.getConnection();
             PreparedStatement pst = conn.prepareStatement("DELETE FROM Employee WHERE Emp_ID = ? AND Role = 'Manager'")) {
            pst.setString(1, id);
            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(view.mainPanel, "Manager Deleted.");
                loadManagerTable();
            } else {
                JOptionPane.showMessageDialog(view.mainPanel, "Manager ID not found.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
